name: Rust

on:
  push:
    branches: [main]
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Install aarch64 toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: aarch64-unknown-none
      - name: Build for QEMU
        run: make build.qemu
      - name: Build for crosvm
        run: make build.crosvm
      - name: Run clippy
        run: make clippy

  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Format Rust code
        run: cargo fmt --all -- --check
